### ISSUE TITLE
xmltest: Replace eines Block liefert unerwartetes Ergebniss

### ISSUE THREAD

**Issue by Hallo32** [xforce/anno1800-mod-loader#10]
Wird `xmltest.exe source.xml patch.xml`ausgeführt ergibt sich patched.xml.

`<foo>
	<bar>
		<baz>1</baz>
	</bar>
</foo>`
`<ModOps>
    <ModOp Type="replace" Path="/foo">
		<bar>
			<foo>1</foo>
		</bar>
    </ModOp>
</ModOps>`

Patched,xml:
` <bar>
    <foo>1</foo>
</bar>`

Das erwartete Ergebnis wäre:
`<foo>
	<bar>
		<foo>1</foo>
	</bar>
</foo>`

[expected.txt](https://github.com/xforce/anno1800-mod-loader/files/3192616/expected.txt)
[patch.txt](https://github.com/xforce/anno1800-mod-loader/files/3192617/patch.txt)
[patched.txt](https://github.com/xforce/anno1800-mod-loader/files/3192618/patched.txt)
[source.txt](https://github.com/xforce/anno1800-mod-loader/files/3192619/source.txt)

**Comment by xforce** [comment]
Aktuell ist das so gewollte, der Path teil in der ModOp sage welche node mit dem content der ModOp ersetzt werden soll.
In dem Fall muesste der Patch dann die foo node auch enthalten, ob das so 100% sinn match ist natuerlich diskutierbar.

**Comment by Hallo32** [comment]
Danke für die Antwort
