### ISSUE TITLE
Mod loader not working

### ISSUE THREAD

**Issue by WoistdasNiveau** [xforce/anno1800-mod-loader#103]
Since the last update Anno 1800 tells me every time, that the current Version is not working with Anno 1800. And that i should upgrade to version 0.8.0 even though i have 0.8.2 installed!?

**Comment by chihsun** [comment]
Could Anno 1800 update 12 detect modified file of mod-loader 0.82 ? Ubisoft Connect downgrades Anno 1800 to version 11 'daily' and it causes non-match version with mod-loader 0.82. I needed to manually verify files or delete mod-loader and re-start Ubisoft Connect to upgrade again.

**Comment by WoistdasNiveau** [comment]
While checking for the version i foudn out that i installed the mod loader to the folder where anno 1800 was installed the last time. Now it is instaleld somewhere else and when installing it to the right file it actually works. So i am just a pro. Thank you very much for your help and you beautiful mod loader.

**Comment by JoePala** [comment]
Did you have two installs of Anno 1800?  Where did you finally install the python dll's?

**Comment by stevenraemaekers** [comment]
After updating to the latest version of Anno 1800, the mod loader stops working, but me it doesn't tell that I should upgrade to anything, just that my current version of the mod loader is incompatible.

**Comment by MadmanHS** [comment]
After automatic (background) updating to the latest game version (high life patch + hotfix) the modloader seems to be imcompatible with the game. Everytime I copy the latest python35.dll into the folder as usually done, the game starts with the window that the modloader needs to be updated and if I want to go to github to download or report an issue (you know which window I mean).
Strangely the game then downgrades back to before "high life" - version 11. That means it kills somehow the updates of 2.2GB and also the last hotfix (>450MB). Any help for this? Thanks in advance. I don't want to go back to vanilla...

**Comment by chihsun** [comment]
@xforce Daily automatic downgrade and upgrade is happened since Sep 1 in the most users in my community group (seem happened only on users with mod-loader), all with Chinese setting, but I do not know if it has also something wrong with locale, just like initial release version, 0.80. And Was no similar problem happen in other locale setting ? Thanks.

**Comment by sk8jamvideos** [comment]
help my anno 1800 mod loarder not working since new High Life update
