### ISSUE TITLE
Modloader is not compatible

### ISSUE THREAD

**Issue by Cosphi85** [xforce/anno1800-mod-loader#104]
Hi,
the modloader does not seem to be compatible. I should get the latest version on Github. But I already have it. VCredist is installed. Is there any news ?

Greetings

Cosphi

**Comment by BigPlaya** [comment]
same here. can't play the game at all with mods enabled.

**Comment by eequalsfb** [comment]
I am having the same problem since Anno was updated this morning.

**Comment by Havelock404** [comment]
the old version is still working after the ubi update just reapply the .dll files and it should work again!

**Comment by BigPlaya** [comment]
yeah. it finally worked again after that latest update. i was busy. i wasn't even able to play the game for long. that's why i did not posted anything here.

because i also assume, that everyone else also tried it again after that update.

**Comment by therealjohndion** [comment]
What update? How do I get it to work? I am using the game on steam and version 0.8.2 of the DLL but notice no changes when run. Thanks for any help.

**Comment by Havelock404** [comment]
There was a small hotfix a few days ago!
If you placed both dll files in the *\Anno 1800\Bin\Win64 (if you did this before the hotfix replace the files again)
Installed  https://aka.ms/vs/16/release/VC_redist.x64.exe
and copyed your desired mods in too *\Anno 1800\mods

**Comment by Cosphi85** [comment]
I'm sorry, but no version is running. The last and penultimate cause the game to crash on me without error.
I specially reinstalled the PC, VCredist on it and then tried.

**Comment by Havelock404** [comment]
Could try to clear the .cache file in \mods let uplay verify the game files then reappply the modloaders dll files.
but i am just guessing here sorry

**Comment by Cosphi85** [comment]
Cleaning the cache helped. Game runs with version 0.8.2.

**Comment by therealjohndion** [comment]
It unfortunately didn't help me. I deleted the .cache folder, I verified files in uplay, i copied the dlls, my mod folder is in the main dir, and my dlls are in Win64\ But anno just starts normally. I have the spice it up mod and just 2 or three others, im not sure what these mods change but I don't notice anything offhand to tell if its working or not and theres no notification of any kind. Thanks.

**Comment by jirge71** [comment]
No that doesn't work

**Comment by Cosphi85** [comment]
after a necessary reinstallation of the operating system and installation of Vcredist, the game simply crashes without error message. With the current and previous version of the modloader. There is something wrong. Cache is cleared.

**Comment by xforce** [comment]
This is very likely related to #51
