### ISSUE TITLE
Hello, will there be an update? thanks

### ISSUE THREAD

**Issue by jirge71** [xforce/anno1800-mod-loader#105]

**Comment by stevenraemaekers** [comment]
Yes please can you make an update, it is not working any more after applying the official patches from Ubisoft.

**Comment by Havelock404** [comment]
the old version is still working after the ubi update just reapply the .dll files and it should work again!

**Comment by spodniarz** [comment]
> the old version is still working after the ubi update just reapply the .dll files and it should work again!

Hmmmm, for its not working :x

**Comment by Havelock404** [comment]
Check #104
