### ISSUE TITLE
DX12: Game isn´t loading even it´s own original dds files

### ISSUE THREAD

**Issue by kskudlik** [xforce/anno1800-mod-loader#11]
The title speaks for itself. When trying to load the original dds file which was extracted from the rda the game just shows nothing where the texture should be. Everything else works fine (no crash etc.)

I did, however, rework the texture files from PR #8 with RC7 and the according mipmap counts. So they are working now as expected in DX11 on all texture quality settings. But obviously not in DX12 because the game currently doesn't even load its own dds files. So I´m waiting to PR that example again until this issue is fixed.

I will try looking into it myself later but I think you'll be able to analyze this issue much faster.
Thanks a lot in advance.

**Comment by xforce** [comment]
Ah ye, I did have the same when I tested your original PR, this was because I added an extra byte for null terminating to the data the game allocates.
Looks like the DDS loader in DX 12 doesn't like that.

Fix on master.

**Comment by kskudlik** [comment]
it´s working now. thanks for your quick help
