### ISSUE TITLE
Update Needed for GU 13.2

### ISSUE THREAD

**Issue by PhillipAlpha** [xforce/anno1800-mod-loader#117]
Modloader is not working correctly

Edit: https://github.com/xforce/anno1800-mod-loader/issues/117#issuecomment-1040652365

**Comment by killkounter** [comment]
yes finally someone noticed it too

**Comment by cursedsummoner** [comment]
Can confirm, after update I tried the Modloader 0.8.3 release and mods are broken.

**Comment by jasonbuff** [comment]
yes plz fix

**Comment by MxGemini31** [comment]
Hey comment je peux mettre à jour moi aussi ca me dit que c'est plus compatible je galère un peu la

**Comment by jasonbuff** [comment]
Bless you and your family you are most appreciated

**Comment by XRoofusX** [comment]
can someone fix the problem with gu 13.2? ;(

**Comment by SomeoneElsexx32** [comment]
What a perfect timing... i just got it and it doesn't work with the mods xD

**Comment by joelzhl** [comment]
Installed Anno on a new OS and forget to uncheck the auto-update button.

Ubisoft, HOW do you still NOT have game version selection support in 2022? Or at least give us the option to roll-back a patch.

**Comment by Bobzilla322** [comment]
Thank you XFORCE really appreciated! will be looking forward to new patch. Same issues here about 4 to 5 hrs been through everything to no avail.

**Comment by xforce** [comment]
Version 0.8.4 with Support for GU 13.2 is now available. <https://github.com/xforce/anno1800-mod-loader/releases/tag/v0.8.4>

**Comment by Bobzilla322** [comment]
Sent you 10.00 because  5 was too far to reach on keyboard..LOL

**Comment by rrosbach** [comment]
game ist not starting for me with the latest update 0.8.3 worked but without mods, 0.8.4 crashes the starting of the game altogether. If there is some information or debugging required, we can connect as I'm also a software dev but just with C# focus :P

**Comment by xforce** [comment]
Crash on startup fixed in 0.8.5 <https://github.com/xforce/anno1800-mod-loader/releases/tag/v0.8.5>
Sorry about that.

**Comment by seanrdmedia** [comment]
Hi thanks for all your hard work. Im sorry if this sounds dumb, but I'm quite new to this. I don't seem to be able to access any mods anymore, I've installed the newest update above, do i need to re-install the original as well? The game plays normally but without any mods. Not sure if i'm doing something wrong. Any help would be appreciated

**Comment by jasonbuff** [comment]
Your the best sorry for the nuisance
