### ISSUE TITLE
0.8.4

### ISSUE THREAD

**Issue by PogoMan361** [xforce/anno1800-mod-loader#121]
Supervielen Dank für das schnelle Update... Nur leider startet Anno jetzt nicht mehr. Alle Mods sind raus, alles lief super vorher...

**Comment by Myterian** [comment]
Kann ich bestätigen. Mit oder ohne Mods, das Spiel stürzt direkt beim Start ab

**Comment by joelzhl** [comment]
Same here, immediate crash to desktop.

All mods removed -> game crashes
Verify game file -> repair -> game launches no problem
Unzip mod-loader to bin folder -> game crashes

**Comment by ratdago** [comment]
do the python files need to be put back in?

**Comment by xforce** [comment]
Sorry. 
I'm aware. Made a mistake. Fix is almost ready.

**Comment by xforce** [comment]
Fixed in 0.8.5 <https://github.com/xforce/anno1800-mod-loader/releases/tag/v0.8.5>

**Comment by rrosbach** [comment]
Danke :) Cooler Fehler btw :D
