### ISSUE TITLE
Old Version is still open in Anno 1800

### ISSUE THREAD

**Issue by Vincent-baar** [xforce/anno1800-mod-loader#122]
I downloaded the new Update for the 13.2 Version of the game and tres to overwrite the 2 files but it says that "the action can't be completed because the file is open in Anno 1800."
Do I have to reinstall the game? Any advice for me? :)

**Comment by rrosbach** [comment]
Try to close everything of the game/ubisoft via task manager. That should do the trick.

**Comment by Vincent-baar** [comment]
Oh I forgot to thank you very very much XFORCE! Your almost immediate updates and support is amazing, thank you :)

**Comment by Vincent-baar** [comment]
Thanks rrosbach
It worked now with the new version :D
