### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by ratdago** [xforce/anno1800-mod-loader#124]
thank you so much for the quick fix for 13.2.
My issue is I cant get the Settings screen to come up. Always blank.
My 1st download was a couple weeks ago, on Windows 11 also
![AMM - Settings 2_16_2022 10_16_01 AM](https://user-images.githubusercontent.com/41763560/154329944-dc6f09a3-fea7-4a04-99e3-c1da986edc63.png)

**Comment by xforce** [comment]
Hey, the software in the screenshot is not create by me, so I can't help you with that. You will have to contact the Author(s) of that program for assistance

**Comment by ratdago** [comment]
oops sorry, thanks
