### ISSUE TITLE
Anno 1800 mod loader

### ISSUE THREAD

**Issue by Cuttyhunker** [xforce/anno1800-mod-loader#127]
I cannot get this new update into my game to work properly. It always tells me the game is open and I cannot replace the files. The game refuses to launch, and I go to Task manager and end Ubisoft processes, but still cannot replace the files. I am totally frustrated by this, and if I knew how to delete the whole mod system out of my system, I would. I'm old and just don't know how to do these things. I enjoy the mods, but this updating thing is a real hassle to me, as I am not knowledgeable enough to fix this type of problem.

**Comment by han19860925** [comment]
thank you!

**Comment by Cuttyhunker** [comment]
I think problem has at least 2 issues. 1 I am using 2070 Nvidea card, and anno has issues with this card and using Directx 12. I tried to uninstall all mods and mod-loader, and when I restart game, it tells me I need to go here to get stuff updated, then I say no, after 15 seconds or so, game will begin, but it is starting in DirectX11. I don't know where the residual files that keep telling me to go here and update are, or I would remove those. I will come back and get the mods again, once I hear Anno has this issues with Nvidea 2070 and Direct X 12 ironed out.
