### ISSUE TITLE
In game issue

### ISSUE THREAD

**Issue by fymtos** [xforce/anno1800-mod-loader#129]
Hello,

the mod is working, but i have a problem that i can't chop wood. I am able to build the board building but not the wood building.
Without this mod i am able to build those buildings. Seems like a bug ?

![Screenshot 2022-04-12 195421](https://user-images.githubusercontent.com/103528537/163024111-b354b300-f832-4ea9-a593-5d3fa85b0333.png)

**Comment by xforce** [comment]
For individual mod issues, please contact the mod author.
