### ISSUE TITLE
ANNO1800 Crashes with mod-loader v 0.8.6

### ISSUE THREAD

**Issue by Starbuck56** [xforce/anno1800-mod-loader#130]
I just installed the update to ANNO1800 version 14.0.1097495
I downloaded your newest mod-loader v 0.8.6
With you modloader dll program installed my ANNO game crashes. It only starts up with the original python35.dll
Can you solve this issue? Or please tell me what to do next. What to upload? I am new here

**Comment by Divfata** [comment]
For me  i canot switch the file in the win64 python35 and 35_ubi

**Comment by Misschaoz1** [comment]
I've got the same problem. The game always crashes during the start, since I installed mod-moader v 0.8.6
It only works with the former version 0.8.5, but after the game update the mods won't work with that version

**Comment by FileNotFound98** [comment]
same problem here. first i couldn't switch the python files but i deleted the old ones and then it worked for me. but after that the game crashes during start up

**Comment by sinan32798** [comment]
Also crashes on launch

**Comment by xforce** [comment]
To verify this is actually an issue with my stuff.
Please rename the mods directory and try launching the game, also known as, no mods installed.

**Comment by carolynt98** [comment]
I still get the message to download the loader.  I deselected all the mods and still the game won't start

**Comment by Starbuck56** [comment]
I renamed the Mods directory and installed  mod-loader v 0.8.6
The game started normally. There was a new Mods directory created. Is that what you expected? What do we do now?

**Comment by blastpv** [comment]
I cured the crashes by removing the [Ornamental] City_Ornaments_MU_2.0 mod, the problem in my case was in it

**Comment by Misschaoz1** [comment]
I updated Spice it up Mod and then everything worked!

**Comment by IzDaPat** [comment]
Disabling **[Ornamental]City_Ornaments_MU_2.0** stops the crashing for me, as well. My other ~15 active mods don't seem to conflict with this version.

**Comment by Starbuck56** [comment]
That is correct. [Ornamental]City_Ornaments_MU_2.0 is the cause of my problems to. I removed it from the mods directory and the game performed well with all the other mods.
Thanks to all of you, for thinking with me in solving this issue. Issue closed I think
