### ISSUE TITLE
I canot switch file in Win64

### ISSUE THREAD

**Issue by Divfata** [xforce/anno1800-mod-loader#131]
For me  i canot switch the file in the win64 python35 and 35_ubi 
![image](https://user-images.githubusercontent.com/103533309/163039086-19d995df-5815-4da9-8de9-1f6560072437.png)

**Comment by Divfata** [comment]
On the last update before the season 4 i get no problem too copy/paste

**Comment by FileNotFound98** [comment]
i deleted the old python35 and 35 ubi and tried again. that worked for me. but the game crashes during start up after i had installed the new ones

**Comment by xforce** [comment]
Can't help you with windows issues. I don't speak, I think that's french.
Assuming it tells you file is currently being used.
No action can be done for that from my side.
Just make sure there isn't a Anno1800 process running somehow.
