### ISSUE TITLE
Fishery

### ISSUE THREAD

**Issue by tomaslillis** [xforce/anno1800-mod-loader#132]
anyone else have an issue with missing fishery on latest update?

**Comment by dkruck1211** [comment]
I am also

**Comment by pilijevski** [comment]
Also had the same issue, could be due to mod incompatibility like harbor city.

**Comment by xforce** [comment]
This is not the place to report issues regarding individual mods.
Please contact the mod author.

**Comment by tomaslillis** [comment]
i never mentioned an addon?

**Comment by xforce** [comment]
> i never mentioned an addon?

I tested this Update with existing savegames and new games. In all cases the "Fishery" was there, and normal, as expected.
The only case this would be an issue is when you have some mod that is incompatible with GU14, or Ubisoft broke something for your Savegame (which can happen, but I doubt it).
This project doesn't modify any of the game files in a way that would cause something like that to happen, it merely gives other people the opportunity to add things that do modify things, but just the mod loader in itself, doesn't modify any of the games assets or configurations.

**Comment by tomaslillis** [comment]
fair enough, I checked anyways and can confirm that the mod Harborlife was causing the issue. Starting a new game without that mod returned it to normal.  I just needed to be pointed in the right direction, thanks for your help
