### ISSUE TITLE
anno 1800 fisher and some other missing building

### ISSUE THREAD

**Issue by Divfata** [xforce/anno1800-mod-loader#135]
![image](https://user-images.githubusercontent.com/103533309/163069860-f85c7945-859b-4913-9258-02a32ef2b984.png)

did it is the python????? make that

**Comment by Divfata** [comment]
and missing fisher for peasant

**Comment by jf89-tera** [comment]
back to the unmodded game...

**Comment by xforce** [comment]
All these issues are from individual mods that are not compatible with the latest Game Update.

Out of my hands, please contact the authors of the mods you are using for an update.
