### ISSUE TITLE
All lumber jacks are gone after Anno 1800 update and mod-loader v0.86

### ISSUE THREAD

**Issue by heop** [xforce/anno1800-mod-loader#137]
- downloaded and installed Anno Update
- incompatibility message with older mod-loader (as expected)
- installed v0.86
- game started without problems
- all lumber jack huts are gone!

Well, I strongly support preservation of nature, but not in my game! Any one else having this problem?

Thx!

**Comment by Tiltyyy** [comment]
i have a issue, that all fishing farms are gone and i cant rebuild any, but the villagers still require fish ;D

**Comment by xforce** [comment]
This is some mod that is incompatible with the latest game update. Please contact the respective mod authors and ask them for an update.
