### ISSUE TITLE
Mod Loader 8.6 dosen't work

### ISSUE THREAD

**Issue by Kevinatore** [xforce/anno1800-mod-loader#139]
Hey there,

Unfortunately I still get an error message that the Mod Loader (8.6) wouldn't be compatible with the current game.

I made sure that those two python35.dll were pasted correctly and VCRedist I also installed.

Is there something I can do?

Thank you so much and best wishes!

**Comment by ghostface36** [comment]
My Anno dont Start wir 8.6. But i become no error message.

**Comment by Kevinatore** [comment]
Hey there,

Everything's working again. The issue was caused by the Spice it Up mods but since they've been updated today, the problem is luckily solved.
