### ISSUE TITLE
Problems with version 0.8.6

### ISSUE THREAD

**Issue by Eldahgar** [xforce/anno1800-mod-loader#142]
Hello. First of all, thanks for the great job you do with the mod loader.

Second, I am experiencing some issues with the latest version (0.8.6). Since the last patch, without having ANY mods installed, the mod loader creates a series of malfunctions in the game. Many buildings disappear or cannot be created again at all (Woodcutter's cabins, coal mines, rum distilleries, etc).

I would greatly appreciate a hotfix to correct this problem which also happens to several friends of mine.

Thank you very much again and regards.

**Comment by jskafb** [comment]
I'm having the same problem, my fisheries are all gone on the islands and I don't have them on the menu as well

**Comment by Verraco-de-hierro** [comment]
I'm having the same problem.

I would greatly appreciate a hotfix to correct this problem which also happens to several friends of mine.

Thank you very much and regards.

**Comment by garignebean** [comment]
happens to me either , is there a sollution for this yet ?

**Comment by blastpv** [comment]
the verification steps are simple.
1. rename the mods folder to any other name to disable the loading of mods
2. We check the game files.
3. We start, if the problem does not start not in files and fashion, if it starts, point 4 is performed.
4. Download the 0.8.6 bootloader files and run it, if it doesn't start, the problem is in the bootloader. If point 5.
5. We return the mods folder and check the problem with the mod (probably uses the mod of more than one developer)

**Comment by Eldahgar** [comment]
the problem is in the mod loader. not in the mods. not in the mods folder. I currently have the game without any mod. I don't even have the mods folder in the root of the game because I deleted it. However, the mod loader still causes those errors in the game.

Without any mod activated. no mods folder even. The game with the loader mod does not allow building lumberjack huts, fishing, rum distilleries, coal mines... etc, etc...

Obviously the bug is in the Mod Loader, so a review of it would be appreciated, as it is the cause of the bug that so many people seem to be having.

Thank you very much again and regards.

**Comment by blastpv** [comment]
> the problem is in the mod loader. not in the mods. not in the mods folder. I currently have the game without any mod. I don't even have the mods folder in the root of the game because I deleted it. However, the mod loader still causes those errors in the game.
> 
> Without any mod activated. no mods folder even. The game with the loader mod does not allow building lumberjack huts, fishing, rum distilleries, coal mines... etc, etc...
> 
> Obviously the bug is in the Mod Loader, so a review of it would be appreciated, as it is the cause of the bug that so many people seem to be having.
> 
> Thank you very much again and regards.

I am not a bootloader developer. But I wrote you a working instruction on how to fix the problem. perform and enjoy a working game with mods. or continue to be indignant and sit without mods. if you had carefully read the closed ticks, you would have found this solution to the problem. but why is it so hard...
Thank you for your attention

**Comment by Keridos** [comment]
Also: You need to start a new game to verify if the modloader is causing the issue. I have seen defective mods breaking saves where removing them did not help. A new game without those mods but with modloader still installed worked fine for me.
