### ISSUE TITLE
Game Crashes To Desktop

### ISSUE THREAD

**Issue by Dragonfyr** [xforce/anno1800-mod-loader#145]
When loading a save game Anno 1800 just crashes to the desktop. 15/04/2022 23:58 GMT

**Comment by Dez2022** [comment]
same here.

**Comment by blastpv** [comment]
the verification steps are simple.
1. rename the mods folder to any other name to disable the loading of mods
2. We check the game files.
3. We start, if the problem does not start not in files and fashion, if it starts, point 4 is performed.
4. Download the 0.8.6 bootloader files and run it, if it doesn't start, the problem is in the bootloader. If point 5.
5. We return the mods folder and check the problem with the mod (probably uses the mod of more than one developer)

**Comment by Dragonfyr** [comment]
> the verification steps are simple.
> 
> 1. rename the mods folder to any other name to disable the loading of mods
> 2. We check the game files.
> 3. We start, if the problem does not start not in files and fashion, if it starts, point 4 is performed.
> 4. Download the 0.8.6 bootloader files and run it, if it doesn't start, the problem is in the bootloader. If point 5.
> 5. We return the mods folder and check the problem with the mod (probably uses the mod of more than one developer)

What? lol

It's the main 'python35_ubi.dll' and 'python35.dll' files we are waiting for. That's the issue.

**Comment by blastpv** [comment]
complete and enjoy the work of the game or be stubborn and sit and wait

**Comment by blastpv** [comment]
> > the verification steps are simple.
> > 
> > 1. rename the mods folder to any other name to disable the loading of mods
> > 2. We check the game files.
> > 3. We start, if the problem does not start not in files and fashion, if it starts, point 4 is performed.
> > 4. Download the 0.8.6 bootloader files and run it, if it doesn't start, the problem is in the bootloader. If point 5.
> > 5. We return the mods folder and check the problem with the mod (probably uses the mod of more than one developer)
> 
> What? lol
> 
> It's the main 'python35_ubi.dll' and 'python35.dll' files we are waiting for. That's the issue.

complete and enjoy the work of the game or be stubborn and sit and wait

**Comment by Dragonfyr** [comment]
> > > the verification steps are simple.
> > > 
> > > 1. rename the mods folder to any other name to disable the loading of mods
> > > 2. We check the game files.
> > > 3. We start, if the problem does not start not in files and fashion, if it starts, point 4 is performed.
> > > 4. Download the 0.8.6 bootloader files and run it, if it doesn't start, the problem is in the bootloader. If point 5.
> > > 5. We return the mods folder and check the problem with the mod (probably uses the mod of more than one developer)
> > 
> > 
> > What? lol
> > It's the main 'python35_ubi.dll' and 'python35.dll' files we are waiting for. That's the issue.
> 
> complete and enjoy the work of the game or be stubborn and sit and wait

What's your problem dude? I'm not stubborn, i'm just waiting patiently for the update from the modders. Stop wasting my time.

**Comment by blastpv** [comment]
> > > > the verification steps are simple.
> > > > 
> > > > 1. rename the mods folder to any other name to disable the loading of mods
> > > > 2. We check the game files.
> > > > 3. We start, if the problem does not start not in files and fashion, if it starts, point 4 is performed.
> > > > 4. Download the 0.8.6 bootloader files and run it, if it doesn't start, the problem is in the bootloader. If point 5.
> > > > 5. We return the mods folder and check the problem with the mod (probably uses the mod of more than one developer)
> > > 
> > > 
> > > What? lol
> > > It's the main 'python35_ubi.dll' and 'python35.dll' files we are waiting for. That's the issue.
> > 
> > 
> > complete and enjoy the work of the game or be stubborn and sit and wait
> 
> What's your problem dude? I'm not stubborn, i'm just waiting patiently for the update from the modders. Stop wasting my time.

will have to wait a long time. You don't need to fix it. The files are OK. I'll give you a solution. read closed ticks.

**Comment by Dragonfyr** [comment]
Managed to get the game working again (by not following this other guys spam). 

Just copied mods back into main mod file. 
Updated Spice it up mod. 
Everything works again. 
Except my storage and influence being a bit off, which I'll fix later.

**Comment by Kevinatore** [comment]
> Managed to get the game working again (by not following this other guys spam).
> 
> Just copied mods back into main mod file. Updated Spice it up mod. Everything works again. Except my storage and influence being a bit off, which I'll fix later.

Hey there,
Yes, installing the latest Spice it Up mod is the key in fact. They just released a new version yesternow and noe everything's fine now.

**Comment by Dragonfyr** [comment]
Yea, mine works but the harbour storage has gone.

Sent from my Huawei phone


-------- Original message --------
From: Kevinatore ***@***.***>
Date: Sun, 17 Apr 2022, 13:34
To: xforce/anno1800-mod-loader ***@***.***>
Cc: Dragonfyr ***@***.***>, Author ***@***.***>
Subject: Re: [xforce/anno1800-mod-loader] Game Crashes To Desktop (Issue #145)

Managed to get the game working again (by not following this other guys spam).

Just copied mods back into main mod file. Updated Spice it up mod. Everything works again. Except my storage and influence being a bit off, which I'll fix later.

Hey there,
Yes, installing the latest Spice it Up mod is the key in fact. They just released a new version yesternow and noe everything's fine now.

**Comment by 43Rageon** [comment]
I disabled all mods and verified game files but it still crashes. I guess there is a problem with the game?

**Comment by xforce** [comment]
Unable to reproduce
