### ISSUE TITLE
Anno 1800 mod loader stopped working his morning

### ISSUE THREAD

**Issue by bmilton5** [xforce/anno1800-mod-loader#156]
Anno 1800 mod loader worked fine yesterday but this morning it won't start and is pointing to compatibilty issue with current version

**Comment by bmilton5** [comment]
Update: Version is 14.3.1118176

**Comment by KarlThorsten89** [comment]
Yeah, the mods seem to load properly when launching via Steam or Ubisoft's Uplay launcher. Pressing Play in the Anno 1800 Mod Manager won't launch the game anymore. Very odd. But it worked 2 days ago for me.
The DLL files I think MUST be updated here if it's to be properly fixed, I think, but the author of the files is too busy with other stuff at the moment, from what I gathered.

**Comment by TheDragon2204** [comment]
I am getting the same issue, except the mods wont launch when starting the game via Uplay.. Is there an alternative way to get them to work until this mod is updated?

**Comment by KarlThorsten89** [comment]
Update for the issue on MY END, at least: It doesn't work running via Steam install, so I can only run mods via Uplay's version of the game. Installing the Steam side of it doesn't work anymore. Issue seems random, as others can run the mods via the Steam install. Weird.

**Comment by TheDragon2204** [comment]
I dont have the steam instal, only play. Well i guess its just a waiting game then

**Comment by bmilton5** [comment]
My game started to work via Uplay a couple of days later and steam stopped working instead so I think this issue maybe isn't due to the mods actually. I recommend installing both steam and uplay so you can jump between them as one of them often will work (my experience anyway)

**Comment by KarlThorsten89** [comment]
I think it's almost safe to say the DLLs here aren't going to get updated again.

**Comment by xforce** [comment]
> I think it's almost safe to say the DLLs here aren't going to get updated again.

That's incorrect

**Comment by xforce** [comment]
same as #51, closing as duplicate
