### ISSUE TITLE
Files included with `<Include>` should not through "failed to get original file" error

### ISSUE THREAD

**Issue by jakobharder** [xforce/anno1800-mod-loader#164]
A file included with `<Include>` is not meant to be applied to any original file on its own, hence the following error doesn't make sense in that case.
> Failed to get original game file data\config\export\main\asset\assets-cheese.xml

**Comment by jakobharder** [comment]
Options I currently see:
- Recommend to name files as `*.include` to avoid the error. They would end up in the game file system, but are harmless.
- Add e.g. `*.include.xml` as a filtered type
- Pre-load all `*.xml` first, mark mentioned includes as not applicable and then do the real load. This one has additional complexity due to caching
- Add an attribute to `ModOps`

My preference out of those is `*.include.xml`. Simple and fast. The attribute is not bad either.

**Comment by xforce** [comment]
Doing `*.include.xml` is probably the best path here. That should be relatively simple and I don't see it ever clashing with game paths, so we could probably also just check whether the game path exists and give that a higher priority just in case, maybe.

**Comment by xforce** [comment]
Fixed in [2b4bac3](https://github.com/xforce/anno1800-mod-loader/commit/2b4bac3386db92155e78e312dae1d66dd0db16d1)
