### ISSUE TITLE
Mod-Loader Needs Update for New DLC 12 release 8 dec 2022

### ISSUE THREAD

**Issue by jacquesmail2** [xforce/anno1800-mod-loader#181]
Mod-Loader Needs Update for New DLC 12 release 8 dec 2022

I know it might take time, Will Wait. Thanks
Also want to say great Work for all the Updates in the Past. Its been Great.

**Comment by auddie2015** [comment]
Next post down he said he is working on it.

**Comment by jasonbuff** [comment]
doesnt look like will get it today prolly have to wait till tommorrow or longer

**Comment by xforce** [comment]
Duplicate of #180
