### ISSUE TITLE
no fire house or police station

### ISSUE THREAD

**Issue by jasonbuff** [xforce/anno1800-mod-loader#182]
still arent buildable

**Comment by jimz011** [comment]
@jasonbuff you marked this as completed, could you maybe post the solution?

**Comment by RicciM-CZ** [comment]
I´m also havin´ same problem - cant build up any police, fire station nor hospital in modded game. So I used modded buildings to substitute functions of vanilla buildings but in story line Iron tower I have to build up police station and game probably awaits for  specific building ID placing so I can´t progress.

**Comment by jasonbuff** [comment]
Yes i figured out it was a mod that caused the firehouse to do this have you updated spice it up mod

**Comment by jasonbuff** [comment]
I updated some mods and it seemed to fix it there are still some mods that have not been updated in quite awhile you might just have to live without

**Comment by jasonbuff** [comment]
Also make sure you have the latest version of mod manager and the latest python files

**Comment by RicciM-CZ** [comment]
Hi, just figured out vanilla buildings are normally available in New World and Enbesa but not in Old world and Cape Tr. They appeared only today after I updated several spice it up mods I do use

**Comment by RicciM-CZ** [comment]
mod manager and pythons are updated AFAIK

**Comment by jasonbuff** [comment]
Hey do you have twitch I can talk u thru it

**Comment by jasonbuff** [comment]
Jasonbuff on twitch I'm streaming the game soon

**Comment by RicciM-CZ** [comment]
yes   I´m jamalalicha there
