### ISSUE TITLE
new patch released for anno

### ISSUE THREAD

**Issue by jasonbuff** [xforce/anno1800-mod-loader#190]
does this mean we need new python files

**Comment by SerikaG** [comment]
seems we need.the new update just broke my game after restart it, with my ubisoft connect

**Comment by jasonbuff** [comment]
seems to work fine once i just replaced the python files

**Comment by SerikaG** [comment]
> seems to work fine once i just replaced the python files

 yeah i just find it is the ubisoft connect's problem, somehow it crashes when try to update my anno 1800, not the mod loader's issue.
