### ISSUE TITLE
GU17 release and ModLoader version 0.9.4 not compatible

### ISSUE THREAD

**Issue by Talagad** [xforce/anno1800-mod-loader#214]
Hi,

when I will start the game (GU17 is installed) than I only get the message tht the loader is not compatiblewith the game :(

Please could you fix it?

Many thanks and regards
Markus

**Comment by Talagad** [comment]
Here an screenshot:

https://prnt.sc/H4SuvP1JPqFk

**Comment by Red20082090** [comment]
same here, please fix, thanks!

**Comment by mjg42** [comment]
+1 thank you so much if you are able to update!

**Comment by shram13** [comment]
same here, thank you so much if you are able to update!

**Comment by adjagu** [comment]
Don't need these .dll's any more. Vanilla game .dll's  allow modding now.  Delete mod loader, verify files, and then start the game. Should be good to go then.

**Comment by Red20082090** [comment]
> Don't need these .dll's any more. Vanilla game .dll's allow modding now. Delete mod loader, verify files, and then start the game. Should be good to go then.

it works！thank you so much!

**Comment by truesanteria** [comment]
> > Don't need these .dll's any more. Vanilla game .dll's allow modding now. Delete mod loader, verify files, and then start the game. Should be good to go then.
> 
> it works！thank you so much!

Do your mods work also? I am able to start the game after verifying the files and my mods no longer are in the game, but they remain in the "mods" folder in game directory. Any advice?

**Comment by Red20082090** [comment]
> > > Don't need these .dll's any more. Vanilla game .dll's allow modding now. Delete mod loader, verify files, and then start the game. Should be good to go then.
> > 
> > 
> > it works！thank you so much!
> 
> Do your mods work also? I am able to start the game after verifying the files and my mods no longer are in the game, but they remain in the "mods" folder in game directory. Any advice?

all my mods are working just fine. after I delete the mod loader, and verified the files, I started the game. The game pops up a page says if I want to use mods or not, I clicked yes. then it showed me a list of mods that I'm currently using. Then I load my saves and played with all my mods on. did you delete the mod loader? that may be a problem.

**Comment by truesanteria** [comment]
Hmm, perhaps I did not remove the modloader correctly, as I saw no such screen asking that question...what is the proper way to ensure I have removed the modloader? Thank you for responding.

**Comment by adjagu** [comment]
> > > Don't need these .dll's any more. Vanilla game .dll's allow modding now. Delete mod loader, verify files, and then start the game. Should be good to go then.
> > 
> > 
> > it works！thank you so much!
> 
> Do your mods work also? I am able to start the game after verifying the files and my mods no longer are in the game, but they remain in the "mods" folder in game directory. Any advice?

Yes. I deleted mod loader, verified files, and then started the game. Popup appeared warning about the perils of modding and provided two options. Reject and Accept. I accepted. Next I chose a game save to load and received a new popup stating that my game save was not using all the mods I had installed.  I then made sure every box was checked and then pressed "Continue". After that game loaded and mods were active.

**Comment by truesanteria** [comment]
> > > > Don't need these .dll's any more. Vanilla game .dll's allow modding now. Delete mod loader, verify files, and then start the game. Should be good to go then.
> > > 
> > > 
> > > it works！thank you so much!
> > 
> > 
> > Do your mods work also? I am able to start the game after verifying the files and my mods no longer are in the game, but they remain in the "mods" folder in game directory. Any advice?
> 
> Yes. I deleted mod loader, verified files, and then started the game. Popup appeared warning about the perils of modding and provided two options. Reject and Accept. I accepted. Next I chose a game save to load and received a new popup stating that my game save was not using all the mods I had installed. I then made sure every box was checked and then pressed "Continue". After that game loaded and mods were active.

Gotcha, thank you for your reply. Relative to my last question, is there a way to ensure I've removed the modloader? I can't seem to find anything related to the modloader in my system files, so I have nothing else to delete (seemingly).

**Comment by adjagu** [comment]
@truesanteria I play on steam not sure what you use. For steam here is what I did. I deleted python35.dll from the \Anno 1800\Bin\Win64 directory. Next I verified the game files with steam. Steam replaced the missing python35.dll. Then I just opened the game and did what I posted in my previous comments.

**Comment by truesanteria** [comment]
> @truesanteria I play on steam not sure what you use. For steam here is what I did. I deleted python35.dll from the \Anno 1800\Bin\Win64 directory. Next I verified the game files with steam. Steam replaced the missing python35.dll. Then I just opened the game and did what I posted in my previous comments.

Gah, I should have mentioned I play on Steam also. Thank you very much for your time, this has cleared things up for me and I have it working now. Have a great day.

**Comment by Aleximus1** [comment]
I play on Ubisoft connect, deleted dll, verified files. After that game is back to vanilla, mods is not working. Needs update.

**Comment by Devil-Chew** [comment]
is there a way to fix it on epic game store?

**Comment by cmtaoc** [comment]
删除两个加载器文件
删除mods里面的.cache文件
在steam验证文件完整性
启动
It's very  good
育碧试图告诉我使用额外mod为违规行为，why？见鬼去吧

**Comment by rgroetzer** [comment]
> I play on Ubisoft connect, deleted dll, verified files. After that game is back to vanilla, mods is not working. Needs update.

Don't delete python35_ubi.dll. Didn't work for me at 1st either.

**Comment by Talagad** [comment]
it's working:

Solution:
Vanilla game .dll's allow modding now. Delete mod loader, verify files, and then start the game. Should be good to go then.

**Comment by Yuee98** [comment]
> > I play on Ubisoft connect, deleted dll, verified files. After that game is back to vanilla, mods is not working. Needs update.
> 
> Don't delete python35_ubi.dll. Didn't work for me at 1st either.

Thanks! This solution works well with game on Ubisoft Connection. 

Delete python35.dll while keep python35_ubi,dll. Then verify the game files. Launch the game and you'll find mods work just like before.

**Comment by jasonbuff** [comment]
you sir are a gentleman and a scholar i followed your directions deleting the right .35.dll and then verify when u restart the game it promps you with a mod confirm decline box i acceped and they work thanks so much

**Comment by jasonbuff** [comment]
if anyone else cant figure it out i will be on twich to hlep for a bit jasonbuff under anno 1800

**Comment by Taragonia** [comment]
> I've tried deleting python35.dll but when i verify the files it says that the game has been corrupted and to repair it, when I repair it, it just adds python35.dll back. If i delete it and play the game immediately without verifying a prompt comes up "Cannot open without python35.dll file". 
So confused, help?

**Comment by jasonbuff** [comment]
did you update the game before you did this

**Comment by jasonbuff** [comment]
are you using steam or ubisoft or epic

**Comment by jasonbuff** [comment]
if u want get on twitch and i can try and help u figure it out jasonbuff

**Comment by Taragonia** [comment]
> I am on ubisoft and I accidentally had it set for auto updates so it did already update the game before trying this. The only reason I even noticed was the pop up saying modloader was incompatible when i tried to play.

**Comment by jasonbuff** [comment]
if u want help im on twitch and we can try to figure it out

**Comment by eMatt69** [comment]
How do I verify the files (in Ubisoft Connect version)?

**Comment by jasonbuff** [comment]
Right click on your game in your library hit verify files

**Comment by Funfun91** [comment]
Is the modloader no longer updated at all? I have carried out all the steps twice, but no mods are active. In addition, Anno always crashes for me at the moment.

**Comment by rrosbach** [comment]
> Is the modloader no longer updated at all? I have carried out all the steps twice, but no mods are active. In addition, Anno always crashes for me at the moment.

same here... even completely reinstalled the game and tried just about everything, but with the mod folder in place, its crashing on start... without the folder, the game is starting.

*Playing with Ubisoft connect and having Jakobs Collection mods any a bunch more.

**Comment by jasonbuff** [comment]
Uninstaller mod loader you can. Keep your mods first step delete the
python.dll folder not the ubi one just the python.dll than go to ur game
library and verify game files when you do this start the game it should
detect the mods and prompt you with a yes or no on mods click confirm and
your mods will work if you need help I can jump on twitch and show. U

**Comment by donkey517** [comment]
Having the same issue when I delete the .ddl file and check files it wants me to repair which adds the .ddl file back into the file.  I also am on Ubisoft

**Comment by jasonbuff** [comment]
If your delete the mod loader and delete the right python file and than
click repair it will work do it exactly like that it will add the python
file back but it won't matter cause it works after that

**Comment by donkey517** [comment]
ok I have tried that it did let me play however no mods

**Comment by jasonbuff** [comment]
I been playing since the guy explains it 5 hrs ago and it works jasonbuff
twitch if u need help

**Comment by donkey517** [comment]
are you on now?

**Comment by jasonbuff** [comment]
Yes I just got on

**Comment by rew277** [comment]
not sure for others but for those who use steam, **delete "python35.dll"** and **verify anno files** (check how on the official guide https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB), and don't delete or re-install if you did **"python35_ubi.dll"** from the loader. When you start the game it will ask whether if you will allow your mods.

**Comment by 593165968** [comment]
same here, thank you so much if you are able to update!

**Comment by weitox** [comment]
Hi, also have the problem where I deleted the  .ddl file verified the game files and the game runs normal but without mods.
Mods folder is still there
I'm on Ubi

**Comment by suxkar** [comment]
> Hi, also have the problem where I deleted the .ddl file verified the game files and the game runs normal but without mods. Mods folder is still there I'm on Ubi

Restart the game again, it worked for me

**Comment by weitox** [comment]
> > Hi, also have the problem where I deleted the .ddl file verified the game files and the game runs normal but without mods. Mods folder is still there I'm on Ubi
> 
> Restart the game again, it worked for me

yep tried that already 

but just did the whole deleting verifying again and now it worked 
TY

**Comment by rrosbach** [comment]
for us it was removing mod [Gameplay] Tourists_Alternativ_Buildings_MU and doing the above mentioned removing of modloader python.dll but keeping the ubi version.

**Comment by PapcioChmiel** [comment]
If you've done everything that was written before and the game still won't start, it's probably the fault of the mods. Three hours, one by one, I moved mods from the backup to an empty folder in the game and launched it. I finally found the culprit and the game runs fine. - Ubisoft launcher

**Comment by cos155** [comment]
Hi - please can someone give me an idiots guide step by step.. My game has updated - I've verified files then replaced the modloader ubi file thingy, but now my game just crashed.
Verified files again and it will run, but without mods :( I don't get any pop up stating allow mod files etc. I've re-started half a dozen times and can't get it to run with mods. Please help a dummy....

**Comment by Aleximus1** [comment]
I deleted three dll, verified files and its work! Check, maybe any mod don't supports update. I have the same problem, it turned out two mods crash my game, i deleted their and all ok. I am use Ubisoft launcher.

**Comment by cos155** [comment]
@Aleximus1   which Mods crashed it please?  I may have the same issue.

**Comment by Aleximus1** [comment]
Green_Mile_MU v1.1, but a new version 1.2 has been released and work fine, the other one didn't remember. Try it, if the game crashes, most likely the problem is in some mod.
