### ISSUE TITLE
possibility of replacing/adding entire groups

### ISSUE THREAD

**Issue by taubenangriff** [xforce/anno1800-mod-loader#26]

**Comment by xforce** [comment]
Can we get a bit more background what this should do and why it's needed?

**Comment by taubenangriff** [comment]
for example yesterday I tried to replace the entire group of fertilitysets and ended up having to replace the entire group in which they were on my own.

So the group was like 

<Group>
  <Assets>
     <Asset> 
    .... 
  </Assets>
</Group>

and I had to replace every single  asset individually or delete it. Would have been way easier if I just could replace the entire group by my own using a modop. 
This only needs to work with assets.xml. To select which group you want to replace one might just link the guid of the first asset in the group.

**Comment by xforce** [comment]
Already possible with the correct XPath. There is no need to add something specific for that.
something like
```<ModOp Type="replace" GUID="1234567" Path="../">
_stuff_
</ModOp>```
`/AssetList/Groups/Group/[Assets/Asset/GUID='1234567']` or `//Group/[Assets/Asset/GUID='1234567']` should do the trick.
