### ISSUE TITLE
<BaseAssetGuid> not working

### ISSUE THREAD

**Issue by taubenangriff** [xforce/anno1800-mod-loader#29]
Whenever I try to create an asset which uses an original game asset as baseAssetGuid the game will give me some kind of error, whether it's crash or a building upgrade which does not work.

**Comment by kskudlik** [comment]
I did use base asset GUID in the ai shipyard mod and it worked fine tho. You need to make sure that the asset you want to add is added BEHIND the original asset into the assets.xml otherwise it won’t work or crash. Pleased check if that fixes your issue :)

**Comment by taubenangriff** [comment]
it already is behind the original asset, 1010345 is line 362xxx (whatever) and I am adding it behind 1010347 which is line 363xxx.

**Comment by kskudlik** [comment]
Well that doesn’t sound right, does it?😁

**Comment by xforce** [comment]
If you guys are not getting anywhere I can take a look if you provide code to reproduce, but I am pretty sure that it _should just work_

**Comment by taubenangriff** [comment]
sent you a testmod on discord

**Comment by taubenangriff** [comment]
BaseAsset has to be in front of the ChildAsset.
