### ISSUE TITLE
Epic Store and Steam support

### ISSUE THREAD

**Issue by xforce** [xforce/anno1800-mod-loader#3]
As I currently only have access to the Uplay version, it likely won't work as-is with the Epic or Steam version, no idea if the binary is actually the same or not.

**Comment by kskudlik** [comment]
I´ve got both the steam and uplay version.
either I´m doing something wrong or you´re right and it doesn´t work in the steam version.
I will try in my uplay version and keep you updated. if you want me to uploaded the binary of the steam version or anything else I´d love to help

**Comment by xforce** [comment]
Ye, I just got sent the Steam exe and will check tomorrow if there are any differences.
I will not be able to run it, but the exe should be enough to get what I need.
Thanks for testing.

**Comment by kskudlik** [comment]
can confirm that your last commit works with the steam version.

**Comment by xforce** [comment]
Seems to be working.
