### ISSUE TITLE
Doesn't work with latest DLC "The passage"

### ISSUE THREAD

**Issue by omegarekrut** [xforce/anno1800-mod-loader#36]
Title

**Comment by obrienjc** [comment]
Can confirm, tried v .0.7.4, and game will not launch.

**Comment by qiushanbeikun** [comment]
same here, the game will crash when loading Archive after the DEC10 update.
please please fix, thanks a lot

**Comment by xforce** [comment]
If you guys have AI Shipyard enabled the game will currently crash, we are trying to fix that mod. But that has nothing to do with the mod-loader itself.

**Comment by qiushanbeikun** [comment]
update: 
the "RadiusToZero" mod will crash the game. 
Modifying the XML file is not working, the only solution I have so far is to disable it.
except for the aiShipyard, other mods are working properly for me. (spice it up, ornamentation and some cheat mods)
I also encounter other problems with the 411.66 Nvidia driver, but that's nothing about the mod loader.
