### ISSUE TITLE
Multiplayer with Mods

### ISSUE THREAD

**Issue by eRasus73** [xforce/anno1800-mod-loader#37]
Trying to Coop in Multiplayer with Mods (from the Spice it up package) enabled (and the replaced .DLL-files) gives an error message when my friend tries to join my lobby or when I try to join his. It says "Check Game Version" (roughly translated from German where it says "Spielversion prüfen") Me and my friend both tried different versions of the .DLL-files with no success. Without the .DLL-files we can play together and join each other's lobbies just fine, just none of the mods work in the game as far as we could see until now.
Singeplayer with the .DLL-files works fine and most of the mods seem to work.

We're both on the Steam version of the game. I am on Win7, my friend is on Win10, we both updated the VS 2019 Redist package from Microsoft.

**Comment by xforce** [comment]
Make sure the mods match exactly, as far as I was informed coop should workf if those conditions are met.
