### ISSUE TITLE
Game freezes on Startup - Mod Loader no longer up-to-date?

### ISSUE THREAD

**Issue by DracoDruid** [xforce/anno1800-mod-loader#42]
I'm not sure whether this is my fault or not, but I constantly have the issue that the game freezes on startup (at the initial epilepsy warning).

Is the current version of the loader still fully compatible to the current game version?

**Comment by xforce** [comment]
https://github.com/xforce/anno1800-mod-loader/releases/tag/v0.7.5 Please re-test with this version :)

**Comment by DracoDruid** [comment]
So far so good. But the issue came sporadicly, so I'll have to try a few more times to be sure.

So oder so: Vielen Dank für die schnelle Unterstützung und das Update. Ich hoffe meine Mail war nicht zu aufdringlich. Gruß nach Lüneburg. :)

**Comment by xforce** [comment]
Can we close this? Or is there still an issue?

**Comment by xforce** [comment]
Closing due to no feedback.
