### ISSUE TITLE
Not working after new DLC (Seat of power)

### ISSUE THREAD

**Issue by Tremour88** [xforce/anno1800-mod-loader#43]
Since the update with the latest DLC came out Anno 1800 doesn't launch when using the modified .dll file, as soon as you revert back to the original it loads fine but without the mods.

**Comment by kairacan** [comment]
up

**Comment by Andr3ws** [comment]
same issue

**Comment by ben-hassler** [comment]
same issue here

**Comment by NevermoreSouls** [comment]
same issue

**Comment by Red20082090** [comment]
up

**Comment by PatBmn** [comment]
up

**Comment by trackkman** [comment]
I have the issue as well.

**Comment by StubbiThrash** [comment]
up

**Comment by xforce** [comment]
https://github.com/xforce/anno1800-mod-loader/releases/tag/v0.7.5 Pre-release waiting further testing. Full release probably tomorrow with update notification and all that.

**Comment by obrienjc** [comment]
Just tried out .75. Anno 1800 loads, but my savegame does not. It loaded with the 12 items per trader mod. Did not load with Spice it up. Crashes to desktop.

**Comment by xforce** [comment]
Hmm, could be something spice it up specific. Some updates change things that are unfortunately not really compatible, but that is out of scope of this project.
Main thing is that the loader itself works, if you have issues with specific mods it is best to get in contact with the authors of those mods directly. (there is a discord for that 😄 )
@obrienjc

**Comment by xforce** [comment]
@obrienjc Actually, there may have been an issue with the version. I have fixed it an re-published, so if anyone has experienced crashes with 0.7.5, please re-download from the releases page and test again, sorry for the inconvenience.

**Comment by Red20082090** [comment]
> @obrienjc Actually, there may have been an issue with the version. I have fixed it an re-published, so if anyone has experienced crashes with 0.7.5, please re-download from the releases page and test again, sorry for the inconvenience.

Just here to say you really don’t need to be sorry, even just for the formality. You did a good job and I really want to thank you for that. Also, I downloaded the previous 0.7.5, it worked fine. I will post here if there is anything glitch.

**Comment by obrienjc** [comment]
Just tried latest version. Loaded fine! Thanks!

**Comment by NevermoreSouls** [comment]
It worked. All of my mods work well. Thanks !

**Comment by Andr3ws** [comment]
Working so far 👍

**Comment by DracoDruid** [comment]
Is that new that the main game menu now displays "Modding Detected" below the "Quit Game" button or has this always been there?

**Comment by SpookHB** [comment]
It was there before ...

**Comment by trackkman** [comment]
It works great! Thank you for your fast fixing! I really appreciate your work

**Comment by DracoDruid** [comment]
> 
> 
> It was there before ...
> 
> xforce- Big Big thanks

Never noticed. Thanks for clarifying.

@xforce : You Sir, are a scholar and gentleman. If you give me your paypal.me, I'll let you have a drink on me. :)

**Comment by Gipfelatom** [comment]
Hey! First great work. However since about 5 hours ago the mod loader does NOT work anymore. I played yesterday and a bit earlier today on the new dlc and GU7. Happened recently, redownloading not working as well. It seems like #47

**Comment by madknine** [comment]
I had the same issue, was working fine, went to play this evening started getting the Not valid message. Restarted computer and it then worked again, played for a few hours, all was fine, closed game down, reloadfed about and hour later got the 'Not valid' again. Reinstalled, removed mods, still got the same issue.

**Comment by fanatictentacle** [comment]
Same here, the loader says my game version is not compatible, though I am on the latest update of the game and loader version

**Comment by xforce** [comment]
[Version 0.7.7](https://github.com/xforce/anno1800-mod-loader/releases/tag/v0.7.7) is now out, which hopefully fixes those issues.
Let me know if there are any more issues :)

**Comment by fanatictentacle** [comment]
Looks like its working again, thanks for the quick update!

**Comment by xforce** [comment]
Since I haven't heard any negative feedback since 0.7.7 I am going to close this issue. If you encounter any issues feel free to open a new one.
