### ISSUE TITLE
.76 broke my mods?

### ISSUE THREAD

**Issue by obrienjc** [xforce/anno1800-mod-loader#48]
Really stumped on this. 

I installed .76. Saw that hot reload was fixed, so I edited one of my mods while the game was running. Updating some trader inventory. Did this all the time in previous versions (> Update 7, .75) without issue.

With .75, I had to reload the game every time. In .76, after closing the file, game crashed.

Now my mods don't work. I've deleted the cache folder, deleted the mods, re copied the mods, nothing. I've downgraded to .75, nothing.

Edit: I went to an older save, and cargostorage and commuter pier seem to be working again. Very bizzare. Not only were they no longer placed in a recent save, there was no option to build them, even though they were enabled and showed no errors in the modloader log.

**Comment by xforce** [comment]
Hmm, odd. Currently have now idea how that broke a savegame. Though the hot-reload thing has always been sometimes a bit funky (it is just me exposing some internal functionality they have, which is not guaranteed to work 100% reliably).

**Comment by obrienjc** [comment]
I don't have the broken savegame anymore, but I -think- perhaps when it broke, the game forgot I had met the threshold to place the modded assets. The icon to place them wasn't there, at all. Commuter pier for workers, for example. Could be it would've re-enabled had I upgraded a residence to worker level again.

**Comment by obrienjc** [comment]
FYI, hotloading still crashes the game

**Comment by xforce** [comment]
Hot-reload works fine on my machine. But as noted before there can be things where it fails, unfortunately there is nothing I can really do about it, I am just calling the functions they use for internal development to not have to restart the game all the time.

**Comment by obrienjc** [comment]
I wonder what either spice it up or anno has changed before and after update 7. Using the same mods, but it always worked fine pre-update.

**Comment by xforce** [comment]
🤷‍♂
