### ISSUE TITLE
[Bug] Patch 7.3 has killed the modloader on my device, has the same happened to anyone else?

### ISSUE THREAD

**Issue by g1g5** [xforce/anno1800-mod-loader#52]
Many thanks to the author for creating this modloader, it has made my Anno 1800 games many times better : )

Sadly the most recent Patch 7.3 appears to have broken it. Is this just for me? or has anyone else also faced this problem?

**Comment by J-a-y-K-a-y** [comment]
Hello there,

can confirm - current version of mod loader not working with the latest Update (7.3) of Anno 1800. I can start up the game itself as usual, but tryig to load into a new or a saved game, I end up in an infinite loading screen. No new mod loader log is created. Restoring the original .dll files fixes the loading issue, but of course you cant use the modular mods that way.

Would love to see a solution - thanks a lot in advance and thumbs up for the great work,
JK

**Comment by xforce** [comment]
Fixed in 1c5e7a6d01a2d29fbdb5f428cdf9bf58860e97e6

**Comment by J-a-y-K-a-y** [comment]
> Fixed in [1c5e7a6](https://github.com/xforce/anno1800-mod-loader/commit/1c5e7a6d01a2d29fbdb5f428cdf9bf58860e97e6)

Greatly appreciated, thx very much!

**Comment by g1g5** [comment]
Many thanks to the author : )
