### ISSUE TITLE
[Bug(?)] Game not recognising DLC and crashing after launch, is anyone else also experiencing this?

### ISSUE THREAD

**Issue by g1g5** [xforce/anno1800-mod-loader#53]
My game launches but does not recognising DLC and crashes soon after. Not sure if this is an issue just at my end or is anyone else is also facing this issue? 

PS
Ahh never mind an update dropped today [link](https://www.anno-union.com/en/balance-changes-coming-with-game-update-8/), so this is probably what broke the loader. Will eagerly await mod loader drop then : )

PS2
I dont suppose the Author has a patreon page?

**Comment by xforce** [comment]
There was no update and mod loader is working fine on my machine.

**Comment by xforce** [comment]
And no, I do not have a Patreon Page.

**Comment by g1g5** [comment]
Must be my installation then, tyvm for the information : )

I will make a donation to the Red Cross in your name!

**Comment by g1g5** [comment]
I cleaned uplay file and canceled cloud sync and the game is working again.

Respectful apologies to everyone for wasting your time, the last few  times this happened was due to update issues : (
