### ISSUE TITLE
mod loader for update 8 

### ISSUE THREAD

**Issue by tony-pang** [xforce/anno1800-mod-loader#54]
Hi, mod loader is currently uncompatible with update 8. 

error msg: 
[2020-06-02 13:35:07.571] [error] Failed to find address in file
[2020-06-02 13:35:07.571] [error] Failed to find address, please create an issue on GitHub 4
[2020-06-02 13:35:08.290] [warning] Address search fall back to file search

Thank you very much :)

**Comment by elemakil** [comment]
Same issue here with repetitions of the same error message for various numbers in the message "Failed to find address, please create an issue on GitHub XX" for XX = (1, 3, 4, 6)

**Comment by xforce** [comment]
Fixed in 87bf479c842014e5d56a29b62020ae0508d82023
Release Coming in a few minutes.

**Comment by tony-pang** [comment]
Thank you for the update 👍

**Comment by xforce** [comment]
See https://github.com/xforce/anno1800-mod-loader/releases/tag/v0.7.9

**Comment by tony-pang** [comment]
works well on my end. thank you very much
