### ISSUE TITLE
Blueprints not getting displayed

### ISSUE THREAD

**Issue by taubenangriff** [xforce/anno1800-mod-loader#55]
blueprints are not displayed when loaded via modloader

**Comment by xforce** [comment]
Please attach a test mod.

**Comment by taubenangriff** [comment]
[[Gameplay] Oil Pier.zip](https://github.com/xforce/anno1800-mod-loader/files/4720233/Gameplay.Oil.Pier.zip)

Oil tank is invisible in blueprint mode.

**Comment by xforce** [comment]
Appears to be fixed, at least in the upcoming 0.8.
If it isn't let me know once it's out 🙂
