### ISSUE TITLE
Deactivated Type

### ISSUE THREAD

**Issue by taubenangriff** [xforce/anno1800-mod-loader#57]
at the moment, I can comment out to deactivate code for testing or temporary removal purposes. 
For a larger ModOp, this can become quite a pain as I have to set comment marks at the beginning, then scroll all the way down and set my end comment mark there. 

A nice to have would be a Type = "deactivated", which would just lead to the modloader entirely ignoring the ModOp. We could also set that as the default type of ModOps, because atm if you make the mistake of leaving out the Type arg, your mod will cause "incompatible game version" errors in multiplayer.

**Comment by xforce** [comment]
Added a `Skip` flag which can be added to a `ModOp` to skip applying said `ModOp` in 49da5fff06d01dc447b47f4196a30df195aba345
