### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by baronstormfist** [xforce/anno1800-mod-loader#58]
hi I put the dll files in the bin folder along with the third and my game crashes I am not using the epic games version if that matters and also the dummy file that im supposed to have does not appear at one time I had that file I was able to load the game with the mods then after modding it further I broke the game I had to reinstall the game im not sure where im messing up any help would be greatly appreciated also if you could supply the dummy file or explain how to get it that would be wonderful

**Comment by xforce** [comment]
I am not sure what you are on about.
The dummy file gets created automatically, that is nothing you have to worry about.
Unfortunately your report lacks a lot of specifics, so just from that there is not actionable info there.

You could add things like, used mods, logs, if possible event viewer output for the crash.

If you require more direct assistance it is always good to join this discord https://discord.gg/NHTX9YZ

**Comment by xforce** [comment]
Due to lack of response, I am closing this for now. If there are further issues, feel free to re-open.
