### ISSUE TITLE
Add game version check

### ISSUE THREAD

**Issue by xforce** [xforce/anno1800-mod-loader#6]
We need a game version check and have to notify the user to update if the version they are using is not compatible.

**Comment by DracoDruid** [comment]
Any news about this?

**Comment by xforce** [comment]
This will be implemented in upcoming 0.7.5. User will be informed if the modloader is not compatible.
Hard to test all possible situations here, but _should_ do the trick.

**Comment by xforce** [comment]
Now part of 0.7.5
