### ISSUE TITLE
Can't change default location for game.

### ISSUE THREAD

**Issue by stahe86** [xforce/anno1800-mod-loader#62]
My game isn't installed in the default path that you list "Uplay default path is C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\games\Anno 1800\Bin\Win64"

Mine is located on the "D:\Program Files (x86)\Anno 1800\mods". How do I change the default location where the mods are pulled from, because no mods work right now.

**Comment by xforce** [comment]
Sorry for late reply.
The mod loader does not care where your game is located.
Just replace the python.dll and you are good to go, everything is done relative to that location.
If your game is not installed at the default location, you obviously have to replace the files in the location where they are on your machine.

**Comment by xforce** [comment]
Closing due to further replies.
