### ISSUE TITLE
Update to 8.2

### ISSUE THREAD

**Issue by DerNigls** [xforce/anno1800-mod-loader#64]
The current Version of the Modloader does not work with the newest Version (8.2.952183)

**Comment by Serpens66** [comment]
> 
> 
> The current Version of the Modloader does not work with the newest Version (8.2.952183)

hm? here it works fine, I can load my mods. Maybe only a specific feature you are using and I'm not is not working? What exactly does not work on your side? I can properly load xml mods.

**Comment by DerNigls** [comment]
when i try to start the game it says that the current Version of the Modloader does not support this Version of Anno 1800

**Comment by xforce** [comment]
What version is that specifically? Steam, Uplay, Epic?
There is a rare bug that sometimes it fails to do certain things on launch where the effect is the same as incompatible version, sometimes restarting the PC fixes it, I am still investigating what causes that, but I am not able to reproduce it locally, so fixing it has proven to be a bit difficult.

**Comment by DerNigls** [comment]
I dont know why but it works now, dont know what i did wrong last time
