### ISSUE TITLE
Anno1800_plus.exe crash after updating to 0.7.11

### ISSUE THREAD

**Issue by imalower** [xforce/anno1800-mod-loader#68]
It says: The application was unable to start correctly (0xc0000142).
            Click OK to close the application.

I looked for any log files for this and couldn't find any. Also for reference, I am using Ubisoft plus to play.
And yes it works before replacing the dll.

Things I've Tried:

I've restarted my PC. 
I've updated my directX and VC.
Ive removed all mods.

Thank you and kind regards.

**Comment by Clownsessen** [comment]
Same here! I am using normal Ubisoft.

Thank your for help!

**Comment by schulzas3** [comment]
Similar issue, just does not startup, without message. Using Uplay.

**Comment by xforce** [comment]
Sorry about this, I wrote some hand optimized code and accidentally checked for the wrong CPU feature, so this happens on older CPUs.
I have fixed this in 7b3edc622186b7576566aca84e58a0e0c0c685aa

Release pending on CI, _should_ be up in a few minutes.

**Comment by devanderhoff** [comment]
@xforce Thanks!

**Comment by xforce** [comment]
Fix now live https://github.com/xforce/anno1800-mod-loader/releases/tag/v0.7.12

**Comment by schulzas3** [comment]
Thanks for your work and you quick support. Works now for me.

**Comment by imalower** [comment]
Thank you very much for the quick response. I really do appreciate your help and dedication.
