### ISSUE TITLE
Error updating the mod manager

### ISSUE THREAD

**Issue by God21420** [xforce/anno1800-mod-loader#69]
When i try to start the mod loader for new mods this message pops up after pressing yes on update "Unhandled unknow exceptions; terminating the application.". After that i get "error reading zip local header".

**Comment by xforce** [comment]
This sounds like a mod manager thing (I am not the developer and not affiliated with any of the manager projects), this is the mod loader. Something entirely different.

**Comment by akkzockt** [comment]
Please **don't** use the old Mod Manager! Check this [README](https://github.com/anno-mods/Anno).

**Comment by Nail42** [comment]
hello guys, i play anno 1800 only with the mods. Thx dear who is programing the mods and mod loaders. 

but with the last update i have a problem: i get 2 times the problemcode  '0xc000142' and it dont start the game. i also install the VC redist but it does not work :(

Please help me

**Comment by Nail42** [comment]
i have to add: my CPU is an older CPU. its AMD Phenom 2 X4 945 Processor

**Comment by xforce** [comment]
@Nail42 this is not the correct place for this, but that CPU is not officially supported by Anno anyways, I am specifically only targeting CPUs that are support by the Anno base game.
So I do make some assumptions on available CPU features, that old of a CPU does not support those. Specifically this now requires SSE 4.2 or AVX currently.
I will see if I can re-enable support for non SSE/AVX code branch....

**Comment by Nail42** [comment]
Okay i have to add that it works with all older Modloaders and Mods from Spice it up.

sry im new on thes portal and my english is not the best :'D

have a good day

**Comment by PhilB62** [comment]
same problem as nail42, problemcode '0xc000142'  game and mods worked fine until last update from ubi
game errors out with 7.12 mod loader, game will run with previous mod loader but mods are not enabled

**Comment by xforce** [comment]
This is not the issue for this.
