### ISSUE TITLE
Patch non XML files 

### ISSUE THREAD

**Issue by lukts30** [xforce/anno1800-mod-loader#7]
One should be able to replace binary files such as dds files  or non xml based text files.

**Comment by xforce** [comment]
You already can. They just can't be patched in memory using some operations, there are currently only XML operations.
https://github.com/xforce/anno1800-mod-loader/blob/master/libs/external-file-loader/src/external-file-loader.cc#L33 

Patched in this case just refers to the ability to modify an existing file with some rules in memory. 
At the moment that is only possible for XML files, all other files will be loaded directly from disk for the mod with the lowest ordered name (mods are loaded alphabetically). If a mod has such a file.

I hope that clarifies it a bit.

**Comment by xforce** [comment]
Also see PR #8
