### ISSUE TITLE
AI Shipyard not working

### ISSUE THREAD

**Issue by RuKuSan91** [xforce/anno1800-mod-loader#72]
Hello,

Since the last Update I am unable to place the AI Shipyard on any Coast.
If i want to do so, there comes the Message "Free Coast needed" even when there is no Building around.
Please help

**Comment by taubenangriff** [comment]
Update to Spice it Up 3.0 and it should be gone.

**Comment by RuKuSan91** [comment]
Okay tryin to do so
thanks

**Comment by xforce** [comment]
This repository is for the mod loader, not to handle issues of individual mods.
As this seems to be a bug with a specific version of a specific mod, I am going to close this.
