### ISSUE TITLE
Can't load any mods

### ISSUE THREAD

**Issue by getout35** [xforce/anno1800-mod-loader#73]
After updating to newest release of the mod loader and playing with no problems for a day, suddenly all my mods stopped working, I removed the old mods, verified the game files, instaled the mod loader again and used only the mods that have been updated after 26/10/2020. Still not working (Mods that i use are Incipium's Tweaks and Enhancements and All items unlocked at traders). After that i tried to load mods one by one but still nothing, Also from time to time a message appears saying that this version of the game is not supported but i am using the latest game version. Also my CPU i above mimimum requirements for the game. Thanks in advance.

**Comment by xforce** [comment]
This sounds like specific mod issues.
For support on a lot of the mods visit https://discord.gg/NHTX9YZ

**Comment by xforce** [comment]
Regarding the incompatible message that is tracked in #51
