### ISSUE TITLE
Game Update 9.2 Support

### ISSUE THREAD

**Issue by acdervis** [xforce/anno1800-mod-loader#76]
The mod loader is not being loaded after game update 9.2

An error message about the modloader not supporting this version is displayed, no message is added to the `mod-loader.log` file.

**Comment by xforce** [comment]
AFAIK this _should_ work.
But could be because of #51

**Comment by acdervis** [comment]
I attempted to start the game again and didn't encounter the issue. Odd. It also seems like my mods are loaded correctly.

I'll reopen this issue if it happens again and there is more to go on.

**Comment by xforce** [comment]
Then it is definitely #51
