### ISSUE TITLE
References to other Patch Files in a single mod

### ISSUE THREAD

**Issue by taubenangriff** [xforce/anno1800-mod-loader#77]
For smaller modifications, having all modops in a single file works well, but for larger mods it quickly becomes a big bunch of ModOps noone really will be able to see through, especially when adding many new assets. 

So it would be great to just reference another file which also contains Mod operations I want to make, which could be as simple as `<Reference Filename = 'data/config/export/main/asset/newships.xml'/>`

You can already kinda do that by having multiple mods, but the problem there is that you ultimatly have to merge them all together for release, since people will probably deactivate stuff they shouldn't deactivate or not copy in all mod folders needed. References to other files would make large mods far easier to structure, develop and install.

**Comment by xforce** [comment]
Sounds like a reasonable thing to do. Will have to see how to do this nicely because right now everything is a sort of overlay over the game files.

**Comment by xforce** [comment]
This will be available in 0.8.0

**Comment by xforce** [comment]
Syntax is as follows:
```<Include File="include_input.xml" />``` 
inside a `ModOps` block to include a referenced file, the file lookup starts at mod folder roo.
