### ISSUE TITLE
python35.dll virus

### ISSUE THREAD

**Issue by 0dae** [xforce/anno1800-mod-loader#78]
Modloader reported as Trojan:Script/Conteban.A!ml "This program is dangerous and executes commands from an attacker."

**Comment by xforce** [comment]
I can assure you there is nothing bad in the pre-built binaries.
I also don't see what would report that. All scans I do on for example `VirusTotal` always come back undetected.

In case you do not trust pre-built binaries. all the code is there, available to compile and review. The only 'binary' component which is in the repository is the `python35_ubi.dll` which itself is just a regular python distribution used to forward python calls to. So you _could_ pick the original `python35.dll` shipped with the game and use that in-place of `python35_ubi.dll`.

There really isn't anything I can do about any third-party tools reporting anything. The best course of action for you would be to report it to the Software Author as a false positive and hope they can adjust their detection.

**Comment by 0dae** [comment]
Thank you for your quick and helpful response,

The file is reported as a Trojan by Microsoft Security Essentials, so I'm
not sure how much of a response i would get from them, if any. Sounds to me
like a false positive but as this is the first instance of any such
occurrence I thought I best report it.

I don't have the library of expertise to check compiled code myself. That
just isn't within my talents so all I could do was reach out to the
authors.

Thanks again for your response
