### ISSUE TITLE
0xc000001d can't start with modloader

### ISSUE THREAD

**Issue by Fidl09** [xforce/anno1800-mod-loader#79]
My friend has the problem that he can't start with modloader enabled. (modloader python35.dll)
He did install VS 2019 Redist.
Pressing start Button and game instant crashing with Error 0xc000001d

After loading original python35.dll into Win64 folder, it worked as usual

Did exact same as i did. (for me it's working)

Any Ideas what it could be?
Greetings Marco

**Comment by prbrowne** [comment]
I had it working yesterday, 28th December, but I get a message stating not compatible with the current version of Anno.  I think there was a game update.

**Comment by xforce** [comment]
@prbrowne That particular issue is tracked in #51 . Difficult to fix because I personally can not reproduce this on my machine, so I am investigating many angles where this issue may be coming from. Generally restarting the game or the pc _should_ be a viable workaround.

**Comment by xforce** [comment]
@Fidl09 See #71

**Comment by xforce** [comment]
Accidentally closed because I was reading the wrong error code.

**Comment by xforce** [comment]
#71
