### ISSUE TITLE
Mod Loader is not working with V9.2.972600

### ISSUE THREAD

**Issue by EdiLung** [xforce/anno1800-mod-loader#80]
Mod Loader is not working with this version
ANNO 1800: COMPLETE EDITION – V9.2.972600 + 10 DLCS
Its cracked version btw.

**Comment by taubenangriff** [comment]
cracked version is your problem.

**Comment by xforce** [comment]
Cracked versions are not supported. If they work they work, if they don't they don't.

Code is available so you debug and fix it yourself.
