### ISSUE TITLE
Mod Loader dont work with Latest edition with all dlc.

### ISSUE THREAD

**Issue by Godassss** [xforce/anno1800-mod-loader#81]

**Comment by xforce** [comment]
What game version is this (9.2.xxxx?).
And where did you buy it? (Steam, Epic, Uplay?)

**Comment by borisyung** [comment]
Same here, I installed Version 0.7.12, but not working on "Anno.1800.Digital.Deluxe.Edition.v9.2.972600"

**Comment by Babagadoosh2021** [comment]
I am also having the same issue. Have UPlay version 9.2.97.2600.

![Error](https://user-images.githubusercontent.com/77111455/103904092-6b5bfc00-50c2-11eb-9049-12344200cd09.jpg)

**Comment by xforce** [comment]
> I am also having the same issue. Have UPlay version 9.2.97.2600.
> 
> ![Error](https://user-images.githubusercontent.com/77111455/103904092-6b5bfc00-50c2-11eb-9049-12344200cd09.jpg)

@Babagadoosh2021 You issue is https://github.com/xforce/anno1800-mod-loader/issues/71, not this one.

**Comment by xforce** [comment]
> Same here, I installed Version 0.7.12, but not working on "Anno.1800.Digital.Deluxe.Edition.v9.2.972600"

@borisyung What store is that from?

**Comment by borisyung** [comment]
uplay

**Comment by Babagadoosh2021** [comment]
> > I am also having the same issue. Have UPlay version 9.2.97.2600.
> > ![Error](https://user-images.githubusercontent.com/77111455/103904092-6b5bfc00-50c2-11eb-9049-12344200cd09.jpg)
> 
> @Babagadoosh2021 Your issue is #71, not this one.

Thank you for the information @xforce. Looking at issue #71, I see that it is in a holding pattern presently for a resolution...Am I correct with that assumption?

**Comment by Cobra-38** [comment]
Same issue here. Playing with UPlay with the newest version of the game.

**Comment by xforce** [comment]
> Same issue here. Playing with UPlay with the newest version of the game.

What error do you get specifically?

"Same Issue" when the original author didn't even tell me what error he gets does not help.
And a plain "doesn't work" is also not helpful.
Details people, details.

**Comment by Cobra-38** [comment]
> > Same issue here. Playing with UPlay with the newest version of the game.
> 
> What error do you get specifically?
> 
> "Same Issue" when the original author didn't even tell me what error he gets does not help.
> And a plain "doesn't work" is also not helpful.
> Details people, details.

It says that the modlader version is not compatible with the game version. Then it asks if i want to check for updates on the website. I found out that a reeinstall solves the problem. At least temporarily.

**Comment by maxknight98** [comment]
can they make a mod loader for the cracked versions? (empress). My country is shit and it's expensive to buy it

**Comment by Stalbay** [comment]
@maxknight98 +++
3rd day I go to the site, hoping that they have updated it for the hacked version

**Comment by xforce** [comment]
> > > Same issue here. Playing with UPlay with the newest version of the game.
> > 
> > What error do you get specifically?
> > 
> > "Same Issue" when the original author didn't even tell me what error he gets does not help.
> > And a plain "doesn't work" is also not helpful.
> > Details people, details.
> 
> It says that the modlader version is not compatible with the game version. Then it asks if i want to check for updates on the website. I found out that a reeinstall solves the problem. At least temporarily.

That is tracked in issue #51

**Comment by xforce** [comment]
As I have already explained in a other issue.
I am not going to add support for a Cracked version.

If it works it works and I am not going to add anything to actively prevent it from working.
If however it doesn't work, which it looks like is the case, then the only thing I can say is:

You have all the code right here in this repository, there is nothing special, debug and fix it yourself, because I won't.

**Comment by 1592363624** [comment]
一样没效果

**Comment by Godassss** [comment]
Hi Alexander, on exe property it says 14.55 and another long number. I replace the files inside the bin folder, but when i launch the game i dont see "modding detected". and i play normal even when i have mods inside the folder.

**Comment by bonecloner** [comment]
Hello, Can i make a request xforce. I am facing similar issues but my game is cracked version. There are many of us wanting to play the games with mods and dont wanna spend 120$ or more for the game with all dlcs. Is it at all possible for you to make a mod loader with crack support. Thank you.

**Comment by Stalbay** [comment]
It's difficult, I think you need a pro here

**Comment by Stalbay** [comment]
> Hello, Can i make a request xforce. I am facing similar issues but my game is cracked version. There are many of us wanting to play the games with mods and dont wanna spend 120$ or more for the game with all dlcs. Is it at all possible for you to make a mod loader with crack support. Thank you.
> I just read your message for cracked support. Can you guide me through as to how to debug myself and fix so i can use it in cracked version. I have never coded but I learn fast.
It's difficult, I think you need a pro here

**Comment by Godassss** [comment]
> > Same issue here. Playing with UPlay with the newest version of the game.
> 
> What error do you get specifically?
> 
> "Same Issue" when the original author didn't even tell me what error he gets does not help.
> And a plain "doesn't work" is also not helpful.
> Details people, details.

Hello, i didnt get any error, after intro video i dont see "modding detected" that's all, the version is 9.2.972600

**Comment by thabans** [comment]
for cracked :  https://www65.zippyshare.com/v/AagdlbNL/file.html
see https://cs.rin.ru/forum/viewtopic.php?f=10&t=82735&start=945

**Comment by artofhyper** [comment]
> 
> 
> for cracked : https://www65.zippyshare.com/v/AagdlbNL/file.html
> see https://cs.rin.ru/forum/viewtopic.php?f=10&t=82735&start=945

worked thanks mate

**Comment by EdiLung** [comment]
> for cracked : https://www65.zippyshare.com/v/AagdlbNL/file.html
> see https://cs.rin.ru/forum/viewtopic.php?f=10&t=82735&start=945

Its working great man... Thanks...

**Comment by xforce** [comment]
Since this seems to be all about cracked versions, I am closing.
