### ISSUE TITLE
Version 0.7.12  does not work with Anno 1800 version 9.2

### ISSUE THREAD

**Issue by Estisch** [xforce/anno1800-mod-loader#82]
New to Anno and new to modding. Wanted to enhance my experience by adding the mods from the community. 

I've copied the modloaders DLL's to the right place to update the mod-loader but keep getting this warning. 

![image](https://user-images.githubusercontent.com/77389983/104446847-b171fd80-55a3-11eb-998b-10fb5269b42c.png)

It either does not find the modloader or the modloader is not compatible?

**Comment by xforce** [comment]
Version 9.2 is 100% confirmed to be fully supported and working across Steam, Uplay and Epic Games launcher.

There is an 'random' issue which results in this message happening some times which is tracked in #51
