### ISSUE TITLE
I am doing something wrong

### ISSUE THREAD

**Issue by jcpayne69** [xforce/anno1800-mod-loader#84]
I was playing the game with mods and using your mod loader with Anno 1800 on Ubisoft. well my computer failed and I got a different one installed Anno and it worked fine. then I installed the latest DLL file you gave and the game will not launch and gives me an error code saying that my files are corrupt. I have tried everything I could think of to make it work so I am hoping you can help me. The Application error actually says; The application was unable to start correctly (0xc0000142). click ok to close program. Thank You for any help you can give me.

**Comment by xforce** [comment]
See https://github.com/xforce/anno1800-mod-loader/issues/71
