### ISSUE TITLE
trying to use Anno 1800 Mdloader 7.5

### ISSUE THREAD

**Issue by apjarnold** [xforce/anno1800-mod-loader#85]
Hi having a problem using the latest version of Mod Loader 7.5 on updated Anno 1800 10.2

It brings up a message box asking me if I want version 0.7.12 when i press NO then box disappears and nothing happens.

![Screenshot 2021-03-31 082357](https://user-images.githubusercontent.com/81675820/113106972-42e42980-91fb-11eb-9883-88832de3e8f0.jpg)

Thank you for all your hard work writing this Mod Loader

**Comment by xforce** [comment]
Mod Loader 7.5? The latest is in fact 0.7.12, that dialog pops up if the internal version if _your_ mod loader is older than the one that latest one available.
So just update?

**Comment by apjarnold** [comment]
Thank you
