### ISSUE TITLE
What does your mod loader send to you?

### ISSUE THREAD

**Issue by Rayxcer** [xforce/anno1800-mod-loader#89]
Hello there,
I've noticed that the modloader sends requests to your website "xforce.dev".
I'd like to know what data it sends, since it does this directly from the game and not as a unique entity (which is a given since it only works via the game, but still).

I'd kindly ask you to specify what and what for it sends these requests.
If you already explained it I'm sorry, I looked for an explanation, but I sadly didn't find one.

Keep up your work. Cheers.

**Comment by xforce** [comment]
It doesn't send anyting, it just requests/downloads <https://xforce.dev/anno1800-mod-loader/latest.json> which is used to detect if there is a new version available.
There is no logging whatsoever on that endpoint.

**Comment by xforce** [comment]
The code can be found here https://github.com/xforce/anno1800-mod-loader/blob/master/libs/python35/src/main.cc#L31

**Comment by Rayxcer** [comment]
I see. Thank you for making things clear.
I hope you can forgive me my mistrust, it just caught me somewhat off guard that Anno was randomly calling your site.

Keep up your great work. Thank you & Cheers.
