### ISSUE TITLE
can´t build the python35.dll

### ISSUE THREAD

**Issue by nousernameno** [xforce/anno1800-mod-loader#9]
first of all thanks a lot for your project, it´s awesome work.

I tried to build it myself with bazel and only got the xmltext.exe but wasn´t able to get the python35.dll needed to get the game loading mods. Isn´t the source for it public or am I doing something wrong?

I´d really appreciate your help.

thanks a lot

**Comment by xforce** [comment]
Can you post the error that you got?

**Comment by kskudlik** [comment]
You could try building this example: 
      https://github.com/bazelbuild/bazel/tree/master/examples/windows/dll
and see if that works.

For me, it works fine using: bazel build //libs/python35:python35.dll
Also, make sure you include all third party stuff just downloading this repos zip won´t include those.

**Comment by nousernameno** [comment]
@kskudlik thank you so much did wrong command now it´s woking
