### ISSUE TITLE
[Bug] Invisible ship bodies when zoomed out

### ISSUE THREAD

**Issue by MrChros** [xforce/anno1800-mod-loader#92]
Hello,
since several months I have installed this nice game again and I wanted to use some mods to spice it up a bit.
Using the mod loaded and mods bascially works with an issue. Ship bodies disappear when I zoom out (or not being fully zommed in):
![screenshot_2021-08-13-22-41-22](https://user-images.githubusercontent.com/41364016/129417661-12608a85-2490-4658-814e-616579e2280e.jpg)

The sails are visible all the time. The issue exists also for other ship types like the flagship (screenshot shows a frigate).
When I fully zoom in, the ship is fully visible:
![screenshot_2021-08-13-22-41-56](https://user-images.githubusercontent.com/41364016/129417053-931e76ca-6733-48b9-9949-48ef6532dc46.jpg)

Here list of mods I'm using:
![image](https://user-images.githubusercontent.com/41364016/129417131-97facda0-e4fe-4c41-b32a-8399f2a47c80.png)

Removing single mods or all mods does not help when the mod loader is used at all.
Not using the mod loader, the issue does not exist and the ships are visible as they should be.

I have installed the game with same mods on two different computers -> exactly the same issue occurs.

My game version is 11.1.1010647 and I'm using version 0.7.12 of the mod loader.

I'm no expert in modding or why such an issue may occur. Using google search I could not find similar issues.

Is there anything I can do from my side to investigate this issue further?
Is there a quick fix available?

Until then, thank you for providing the mod loader at all. It's a great thing and it really boosts this already great game.

Best,
Mr Chros

**Comment by xforce** [comment]
I believe this is related to mods that change lodlevels.
I don't think there is anything in the mod loader itself that I can do to fix it.
